// generated by https://transform.tools/json-to-typescript
export interface CisionNewsfeedResponse {
  PageIndex: number
  PageSize: number
  TotalFoundReleases: number
  TotalFoundMedias: number
  ReleaseFeedIdentifier: string
  MediaFeedIdentifier: string
  Releases: NewsfeedRelease[]
  Medias: any[]
  Title: string
  Author: string
  DatePackaged: string
}

export interface NewsfeedRelease {
  Id: number
  EncryptedId: string
  IsRegulatory: boolean
  SuppressImageOnCisionWire: boolean
  PublishDate: string
  LastChangeDate: string
  Title: string
  Intro: string
  IptcCode: string
  InformationType: string
  LanguageCode: string
  CountryCode: string
  CanonicalUrl: string
  CisionWireUrl: string
  RawHtmlUrl: string
  LanguageVersions: LanguageVersion[]
  Images: any[]
  Tickers: Ticker[]
}

export interface LanguageVersion {
  Code: string
  ReleaseId: number
}

export interface Ticker {
  Symbol: string
  ISIN: string
  PrimaryListing: boolean
  IsShare: boolean
  MarketPlaceSymbol: string
  MarketPlaceName: string
  MarketPlaceIsRegulated: boolean
  MarketPlaceCountryCode: string
}

